 ReplaceUpperEnchantName = function(){
		if (UpperEnchantName == "ACID") {$(this).html("Swift")}
		if (UpperEnchantName == "ADROIT") {$(this).html("Even")}
		if (UpperEnchantName == "ADVENTURER") {$(this).html("Explorer's")}
		if (UpperEnchantName == "ADVENTURER_100") {$(this).html("Explorer's")}
		if (UpperEnchantName == "AGILE") {$(this).html("Lightning")}
		if (UpperEnchantName == "ANTIQUE") {$(this).html("Impending")}
		if (UpperEnchantName == "ANTIQUE_100") {$(this).html("Impending")}
		if (UpperEnchantName == "ATK1000DAY90") {$(this).html("Very Heartless")}
		if (UpperEnchantName == "ATK500DAY30") {$(this).html("꽤 냉혹한")}
		if (UpperEnchantName == "ATK500DAY60") {$(this).html("Quite Heartless")}
		if (UpperEnchantName == "ATK500DAY7") {$(this).html("꽤 냉혹한")}
		if (UpperEnchantName == "ATK50DAY30") {$(this).html("Heartless")}
		if (UpperEnchantName == "ATK50DAY7") {$(this).html("냉혹한")}
		if (UpperEnchantName == "AWKWARD") {$(this).html("Blunt")}
		if (UpperEnchantName == "BALANCED") {$(this).html("Well-balanced")}
		if (UpperEnchantName == "BALANCED_100") {$(this).html("Well-balanced")}
		if (UpperEnchantName == "BEGINNERS") {$(this).html("Disciple's")}
		if (UpperEnchantName == "BERSERKER") {$(this).html("분노의")}
		if (UpperEnchantName == "BITTER") {$(this).html("Relentless")}
		if (UpperEnchantName == "BITTER_100") {$(this).html("Relentless")}
		if (UpperEnchantName == "BLOW") {$(this).html("Fatal")}
		if (UpperEnchantName == "BRAVE") {$(this).html("Brave")}
		if (UpperEnchantName == "CALM") {$(this).html("Focused")}
		if (UpperEnchantName == "CHANGEABLE") {$(this).html("Cautious")}
		if (UpperEnchantName == "CHARMING") {$(this).html("Vibrant")}
		if (UpperEnchantName == "CLEARNESS") {$(this).html("Nimble")}
		if (UpperEnchantName == "CLOSE") {$(this).html("Invincible")}
		if (UpperEnchantName == "CONSTANT") {$(this).html("Aggressive")}
		if (UpperEnchantName == "CRESENT") {$(this).html("Crescent Moonlight's")}
		if (UpperEnchantName == "CRESENT_100") {$(this).html("Crescent Moonlight's")}
		if (UpperEnchantName == "CURIOUS") {$(this).html("Warlord's")}
		if (UpperEnchantName == "CURIOUS_100") {$(this).html("Warlord's")}
		if (UpperEnchantName == "DECEPTIVE") {$(this).html("Intense")}
		if (UpperEnchantName == "DECIDE") {$(this).html("Determined")}
		if (UpperEnchantName == "DECISIVE") {$(this).html("Decisive")}
		if (UpperEnchantName == "DEF1000DAY90") {$(this).html("Very Benevolent")}
		if (UpperEnchantName == "DEF500DAY30") {$(this).html("꽤 자비로운")}
		if (UpperEnchantName == "DEF500DAY60") {$(this).html("Quite Benevolent")}
		if (UpperEnchantName == "DEF500DAY7") {$(this).html("꽤 자비로운")}
		if (UpperEnchantName == "DEF50DAY30") {$(this).html("Benevolent")}
		if (UpperEnchantName == "DEF50DAY7") {$(this).html("자비로운")}
		if (UpperEnchantName == "DELICATE") {$(this).html("Subdued")}
		if (UpperEnchantName == "DURATION") {$(this).html("Consistent")}
		if (UpperEnchantName == "ELEGANT") {$(this).html("Elegant")}
		if (UpperEnchantName == "ENERGY") {$(this).html("Vigorous")}
		if (UpperEnchantName == "ENLIGHTENMENT") {$(this).html("Enlightened")}
		if (UpperEnchantName == "EXPLOSIVE") {$(this).html("Explosive")}
		if (UpperEnchantName == "EXPLOSIVE_100") {$(this).html("Explosive")}
		if (UpperEnchantName == "EXTREME") {$(this).html("Extreme")}
		if (UpperEnchantName == "FAIR") {$(this).html("Fair")}
		if (UpperEnchantName == "FAMILIAR") {$(this).html("Adamant")}
		if (UpperEnchantName == "FINE") {$(this).html("Quality")}
		if (UpperEnchantName == "FINGER_MARKED") {$(this).html("Tactician's")}
		if (UpperEnchantName == "FINISHED") {$(this).html("Balanced")}
		if (UpperEnchantName == "FLASH") {$(this).html("Fleet")}
		if (UpperEnchantName == "FLUTTER") {$(this).html("Eternal")}
		if (UpperEnchantName == "FRESH") {$(this).html("Fresh")}
		if (UpperEnchantName == "HARD") {$(this).html("Bold")}
		if (UpperEnchantName == "HARSH") {$(this).html("Stinging")}
		if (UpperEnchantName == "HP1000DAY90") {$(this).html("매우 관대한")}
		if (UpperEnchantName == "HP500DAY30") {$(this).html("꽤 관대한")}
		if (UpperEnchantName == "HP500DAY60") {$(this).html("꽤 관대한")}
		if (UpperEnchantName == "HP500DAY7") {$(this).html("꽤 관대한")}
		if (UpperEnchantName == "HP50DAY30") {$(this).html("관대한")}
		if (UpperEnchantName == "HP50DAY7") {$(this).html("관대한")}
		if (UpperEnchantName == "INJUSTICE") {$(this).html("Immoral")}
		if (UpperEnchantName == "INJUSTICE_100") {$(this).html("Immoral")}
		if (UpperEnchantName == "INNER_TEST") {$(this).html("젠틀맨")}
		if (UpperEnchantName == "INSIST") {$(this).html("Stalwart")}
		if (UpperEnchantName == "INTELLIGENT") {$(this).html("Sorcerer's")}
		if (UpperEnchantName == "JUSTICE") {$(this).html("Righteous")}
		if (UpperEnchantName == "KNOWLEDGE") {$(this).html("Apprentice's")}
		if (UpperEnchantName == "LEOPARD") {$(this).html("Leopard's")}
		if (UpperEnchantName == "LEOPARD_100") {$(this).html("Leopard's")}
		if (UpperEnchantName == "LIGHT") {$(this).html("Graceful")}
		if (UpperEnchantName == "LIKELY") {$(this).html("Surging")}
		if (UpperEnchantName == "MAGICAL") {$(this).html("Magical")}
		if (UpperEnchantName == "MANA") {$(this).html("Empowered")}
		if (UpperEnchantName == "MULTIPURPOSE") {$(this).html("Endless")}
		if (UpperEnchantName == "NAIVE") {$(this).html("Trusty")}
		if (UpperEnchantName == "ORNATE") {$(this).html("Ornate")}
		if (UpperEnchantName == "PATIENT") {$(this).html("Tenacious")}
		if (UpperEnchantName == "PERSPICUITY") {$(this).html("Hateful")}
		if (UpperEnchantName == "PERSPICUITY_100") {$(this).html("Hateful")}
		if (UpperEnchantName == "PIERCING") {$(this).html("Forceful")}
		if (UpperEnchantName == "POWERFUL") {$(this).html("Powerful")}
		if (UpperEnchantName == "PRECIOUS") {$(this).html("Rounded")}
		if (UpperEnchantName == "PREPARED") {$(this).html("Heavy")}
		if (UpperEnchantName == "PREVENT") {$(this).html("Sturdy")}
		if (UpperEnchantName == "PROPER") {$(this).html("Clear")}
		if (UpperEnchantName == "PROPERLY") {$(this).html("Honed")}
		if (UpperEnchantName == "PROTECTED") {$(this).html("Hardy")}
		if (UpperEnchantName == "PROTECTED_100") {$(this).html("Hardy")}
		if (UpperEnchantName == "PROUD") {$(this).html("Prideful")}
		if (UpperEnchantName == "QUICKNESS") {$(this).html("Quick")}
		if (UpperEnchantName == "RANDOM_TEST") {$(this).html("테스트")}
		if (UpperEnchantName == "RELAXED") {$(this).html("Fitted")}
		if (UpperEnchantName == "REMEMBER") {$(this).html("Memorable")}
		if (UpperEnchantName == "REPEATSAY") {$(this).html("Reinforced")}
		if (UpperEnchantName == "RESOLUTION") {$(this).html("Adjusted")}
		if (UpperEnchantName == "RESOLUTION_100") {$(this).html("Resolute")}
		if (UpperEnchantName == "RICH") {$(this).html("Enhanced")}
		if (UpperEnchantName == "RICH_100") {$(this).html("Enhanced")}
		if (UpperEnchantName == "SERVICEABLE") {$(this).html("Sharp")}
		if (UpperEnchantName == "SHARP") {$(this).html("Tempered")}
		if (UpperEnchantName == "SHARPEDGE") {$(this).html("Keen")}
		if (UpperEnchantName == "SIGNIFICANT") {$(this).html("Significant")}
		if (UpperEnchantName == "SIGNIFICANT_100") {$(this).html("Significant")}
		if (UpperEnchantName == "SILENT") {$(this).html("Silent")}
		if (UpperEnchantName == "SIMPLE") {$(this).html("Fair")}
		if (UpperEnchantName == "SOLID") {$(this).html("Solid")}
		if (UpperEnchantName == "SOW") {$(this).html("SOW")}
		if (UpperEnchantName == "SPEED1DAY30") {$(this).html("Hasty")}
		if (UpperEnchantName == "SPEED1DAY7") {$(this).html("성급한")}
		if (UpperEnchantName == "SPEED2DAY30") {$(this).html("꽤 성급한")}
		if (UpperEnchantName == "SPEED2DAY60") {$(this).html("Quite Hasty")}
		if (UpperEnchantName == "SPEED2DAY7") {$(this).html("꽤 성급한")}
		if (UpperEnchantName == "SPEED3DAY90") {$(this).html("Very Hasty")}
		if (UpperEnchantName == "SPEEDY") {$(this).html("Fast")}
		if (UpperEnchantName == "SPEEDY_100") {$(this).html("Fast")}
		if (UpperEnchantName == "SPEEDY_MOONCAKES") {$(this).html("신속한")}
		if (UpperEnchantName == "STARLIGHT") {$(this).html("Starlight")}
		if (UpperEnchantName == "STARLIGHT_100") {$(this).html("Starlight")}
		if (UpperEnchantName == "STEADY") {$(this).html("Enduring")}
		if (UpperEnchantName == "STOUT") {$(this).html("Strong")}
		if (UpperEnchantName == "STOUT_100") {$(this).html("Strong")}
		if (UpperEnchantName == "STRANGE") {$(this).html("Odd")}
		if (UpperEnchantName == "STRENGTH") {$(this).html("Burly")}
		if (UpperEnchantName == "STRONG") {$(this).html("Driven")}
		if (UpperEnchantName == "STRONG_BODY") {$(this).html("Resilient")}
		if (UpperEnchantName == "STRONG_SHOT") {$(this).html("Fierce")}
		if (UpperEnchantName == "STURDY") {$(this).html("Protective")}
		if (UpperEnchantName == "SUBSTANTIAL") {$(this).html("Unyielding")}
		if (UpperEnchantName == "SURPRISE") {$(this).html("Wild")}
		if (UpperEnchantName == "SWIFT") {$(this).html("Agile")}
		if (UpperEnchantName == "TEST") {$(this).html("Training")}
		if (UpperEnchantName == "THRILLING") {$(this).html("Tricky")}
		if (UpperEnchantName == "TIME") {$(this).html("Temporal")}
		if (UpperEnchantName == "TIME_100") {$(this).html("Time's")}
		if (UpperEnchantName == "TUTELARY") {$(this).html("Tutelary")}
		if (UpperEnchantName == "TUTELARY_100") {$(this).html("Tutelary")}
		if (UpperEnchantName == "TWILIGHT") {$(this).html("Twilight")}
		if (UpperEnchantName == "TWINKLE") {$(this).html("Twinkling")}
		if (UpperEnchantName == "UNDEAD") {$(this).html("The Dead")}
		if (UpperEnchantName == "UNDERDONE") {$(this).html("Gallant")}
		if (UpperEnchantName == "UNDERDONE_100") {$(this).html("Gallant")}
		if (UpperEnchantName == "VALUABLE") {$(this).html("Staggering")}
		if (UpperEnchantName == "WANTLESS") {$(this).html("Fine")}
		if (UpperEnchantName == "WILL") {$(this).html("Daring")}
		if (UpperEnchantName == "WINDY") {$(this).html("Fateful")}
		if (UpperEnchantName == "WISDOM") {$(this).html("Scholar's")}
		if (UpperEnchantName == "WISE") {$(this).html("Mage's")}
		if (UpperEnchantName == "WISE_MAN") {$(this).html("Sage's")}
		if (UpperEnchantName == "WRATH") {$(this).html("Wrathful")}
		if (UpperEnchantName == "AMBITION") {$(this).html("Maelstrom")}
		if (UpperEnchantName == "AMBITION_100") {$(this).html("Maelstrom")}
		if (UpperEnchantName == "AMBITION_MOONCAKES") {$(this).html("야망")}
		if (UpperEnchantName == "AMETHYST") {$(this).html("Command")}
		if (UpperEnchantName == "ANNOUNCEMENT") {$(this).html("Declarative")}
		if (UpperEnchantName == "ARMADILLO") {$(this).html("Armadillo")}
		if (UpperEnchantName == "BASIC_MAGIC") {$(this).html("Speed")}
		if (UpperEnchantName == "BASIC_MANA") {$(this).html("Vitality")}
		if (UpperEnchantName == "BEAM") {$(this).html("Pain")}
		if (UpperEnchantName == "BESTCOUPLE") {$(this).html("베스트 커플")}
		if (UpperEnchantName == "BLIZZARD") {$(this).html("Bulwark")}
		if (UpperEnchantName == "BLOCK") {$(this).html("Energy")}
		if (UpperEnchantName == "CATS_EYE") {$(this).html("Witchcraft")}
		if (UpperEnchantName == "CHANCE") {$(this).html("Chance")}
		if (UpperEnchantName == "COAT") {$(this).html("Dominance")}
		if (UpperEnchantName == "CONVICT") {$(this).html("Spirited")}
		if (UpperEnchantName == "COURAGE") {$(this).html("Frenzy")}
		if (UpperEnchantName == "CRY") {$(this).html("Madness")}
		if (UpperEnchantName == "CURSE") {$(this).html("Rage")}
		if (UpperEnchantName == "DECISION") {$(this).html("Strike")}
		if (UpperEnchantName == "DIAMOND") {$(this).html("Diamond")}
		if (UpperEnchantName == "ECHO") {$(this).html("Echoing")}
		if (UpperEnchantName == "EXPEDITION") {$(this).html("Expeditionary")}
		if (UpperEnchantName == "EXPEDITION_100") {$(this).html("Expedition")}
		if (UpperEnchantName == "FALLENLEAF") {$(this).html("Sentinel")}
		if (UpperEnchantName == "FALLENLEAF_100") {$(this).html("Sentinel")}
		if (UpperEnchantName == "FALLFOLIAGE") {$(this).html("Defender")}
		if (UpperEnchantName == "FATAL") {$(this).html("Deadly")}
		if (UpperEnchantName == "FERVOR") {$(this).html("Enthusiastic")}
		if (UpperEnchantName == "FERVOR_100") {$(this).html("Vivacious")}
		if (UpperEnchantName == "FERVOR_MOONCAKES") {$(this).html("열의")}
		if (UpperEnchantName == "FIGHT") {$(this).html("Resistant")}
		if (UpperEnchantName == "FIRST_STEP") {$(this).html("Agony")}
		if (UpperEnchantName == "FULFILL") {$(this).html("Slayer")}
		if (UpperEnchantName == "GIANT") {$(this).html("Stone")}
		if (UpperEnchantName == "GNOLL") {$(this).html("Gnoll")}
		if (UpperEnchantName == "GOBLIN") {$(this).html("Goblin")}
		if (UpperEnchantName == "GOLEM") {$(this).html("Golem")}
		if (UpperEnchantName == "GRAVEL") {$(this).html("Toughness")}
		if (UpperEnchantName == "HEAVY_RAIN") {$(this).html("Chaos")}
		if (UpperEnchantName == "HIGH_MAGIC") {$(this).html("Brilliance")}
		if (UpperEnchantName == "HIGH_MANA") {$(this).html("Fury")}
		if (UpperEnchantName == "HOPE") {$(this).html("Destiny")}
		if (UpperEnchantName == "ICE_STONE") {$(this).html("Spellcraft")}
		if (UpperEnchantName == "ITINERARY") {$(this).html("Journeying")}
		if (UpperEnchantName == "IVORY") {$(this).html("Resolve")}
		if (UpperEnchantName == "JADE") {$(this).html("Conjuring")}
		if (UpperEnchantName == "JASMINE") {$(this).html("Force")}
		if (UpperEnchantName == "JASMINE_100") {$(this).html("Force")}
		if (UpperEnchantName == "JUDGMENT") {$(this).html("Judgment")}
		if (UpperEnchantName == "KOBOLD") {$(this).html("Kobold")}
		if (UpperEnchantName == "MEDIUM_MAGIC") {$(this).html("Resurgence")}
		if (UpperEnchantName == "MEDIUM_MANA") {$(this).html("Rejuvenation")}
		if (UpperEnchantName == "MIND") {$(this).html("Berserker")}
		if (UpperEnchantName == "MIND_100") {$(this).html("Berserker")}
		if (UpperEnchantName == "MIND_MOONCAKES") {$(this).html("마음")}
		if (UpperEnchantName == "MIST") {$(this).html("Tempest")}
		if (UpperEnchantName == "NOBLE") {$(this).html("Incorruptible")}
		if (UpperEnchantName == "PASSION") {$(this).html("Passion")}
		if (UpperEnchantName == "PASSION_100") {$(this).html("Passion")}
		if (UpperEnchantName == "PERIDOT") {$(this).html("Wizardry")}
		if (UpperEnchantName == "PETAL") {$(this).html("Bloodlust")}
		if (UpperEnchantName == "PETAL_100") {$(this).html("Bloodlust")}
		if (UpperEnchantName == "PETAL_MOONCAKES") {$(this).html("꽃잎")}
		if (UpperEnchantName == "PINE") {$(this).html("Accord")}
		if (UpperEnchantName == "PROTECTION") {$(this).html("Master")}
		if (UpperEnchantName == "PUNISH") {$(this).html("Divine Punishment")}
		if (UpperEnchantName == "PUNISH_100") {$(this).html("Divine Punishment")}
		if (UpperEnchantName == "PVP_ENCHANT_LV40") {$(this).html("Soldier")}
		if (UpperEnchantName == "PVP_ENCHANT_LV50") {$(this).html("Knight")}
		if (UpperEnchantName == "PVP_ENCHANT_LV60") {$(this).html("Bishop")}
		if (UpperEnchantName == "PVP_ENCHANT_LV65") {$(this).html("Rook")}
		if (UpperEnchantName == "PVP_ENCHANT_LV70") {$(this).html("Queen")}
		if (UpperEnchantName == "PVP_ENCHANT_LV75") {$(this).html("King")}
		if (UpperEnchantName == "PVP_ENCHANT_LV80") {$(this).html("Emperor")}
		if (UpperEnchantName == "RAINBOW") {$(this).html("Oblivion")}
		if (UpperEnchantName == "RESOLVE") {$(this).html("Skill")}
		if (UpperEnchantName == "ROCK") {$(this).html("Safety")}
		if (UpperEnchantName == "SAND") {$(this).html("Resistance")}
		if (UpperEnchantName == "SAPPHIRE") {$(this).html("Arcana")}
		if (UpperEnchantName == "SHOWER") {$(this).html("Restoration")}
		if (UpperEnchantName == "SNOWBRANCH") {$(this).html("Might")}
		if (UpperEnchantName == "SPELL") {$(this).html("Suffering")}
		if (UpperEnchantName == "SPRING_RAIN") {$(this).html("Vigilance")}
		if (UpperEnchantName == "SPROUT") {$(this).html("Zeal")}
		if (UpperEnchantName == "STARLIGHT") {$(this).html("Annihilation")}
		if (UpperEnchantName == "STATUE") {$(this).html("Illusion")}
		if (UpperEnchantName == "STIGMA") {$(this).html("Stigma")}
		if (UpperEnchantName == "TEST") {$(this).html("Test")}
		if (UpperEnchantName == "TRESURE") {$(this).html("Ruin")}
		if (UpperEnchantName == "TYPHOON") {$(this).html("Palisade")}
		if (UpperEnchantName == "VALOR") {$(this).html("Valor")}
		if (UpperEnchantName == "VALOR_100") {$(this).html("Valor")}
		if (UpperEnchantName == "VAMPIRE") {$(this).html("Vampire")}
		if (UpperEnchantName == "VITALITY") {$(this).html("Healthy")}
		if (UpperEnchantName == "VITALITY_100") {$(this).html("Healthy")}
		if (UpperEnchantName == "WAVE") {$(this).html("Savvy")}
		if (UpperEnchantName == "WEAK") {$(this).html("Striking")}
		if (UpperEnchantName == "WHISPER") {$(this).html("Misery")}
		if (UpperEnchantName == "WILLOW") {$(this).html("Refuge")}
		if (UpperEnchantName == "YETI") {$(this).html("Yeti")}
}