ReplaceBattles = function (){
$('.storygoal').each(function() {
		NewBattles = $(this).html();
		NewBattles = NewBattles.replace(/{QUEST_BEAR_GIANT:quest}/gi, "<span class='quest'>[Frosted Omen]</span>")
		NewBattles = NewBattles.replace(/{QUEST_BEAR_GIANT_EVENT:quest}/gi, "<span class='quest'>[징후]</span>")
		NewBattles = NewBattles.replace(/{QUEST_BEAR_NORMAL:quest}/gi, "<span class='quest'>[Dethrone the White Tyrant]</span>")
		NewBattles = NewBattles.replace(/{QUEST_BEAR_RETURN:quest}/gi, "<span class='quest'>[White Tyrant's Challenge]</span>")
		NewBattles = NewBattles.replace(/{QUEST_BEAR_RETURN_EQUAL:quest}/gi, "<span class='quest'>[폭군의 도전]</span>")
		NewBattles = NewBattles.replace(/{QUEST_BEAR_URKUL:quest}/gi, "<span class='quest'>[Irukul]</span>")
		NewBattles = NewBattles.replace(/{QUEST_BEAR_URKUL_EQUAL:quest}/gi, "<span class='quest'>[우르쿨]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CHARLES_RACE:quest}/gi, "<span class='quest'>[The Charles Challenge]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CHARLES_TRAIN:quest}/gi, "<span class='quest'>[Charles Expedition]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRAGDIGGER_QYRMIGAL:quest}/gi, "<span class='quest'>[Frost Stones]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT:quest}/gi, "<span class='quest'>[Crescent Moon Island]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_EQUAL_KIERU:quest}/gi, "<span class='quest'>[초승달 섬: 여족장 키에루]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_EQUAL_ZAKARUM:quest}/gi, "<span class='quest'>[초승달 섬: 지진술사 자카룸]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_KARU:quest}/gi, "<span class='quest'>[Wasp Hive]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_KIERU:quest}/gi, "<span class='quest'>[The Chief of Death]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_RAKIORA:quest}/gi, "<span class='quest'>[Serpent King Lakoria]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_RAKIORA_DS:quest}/gi, "<span class='quest'>[맞설 수 없는 존재]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_RAKIORA_DS_EVENT:quest}/gi, "<span class='quest'>[맞설 수 없는 존재]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_RAKIORA_EQUAL:quest}/gi, "<span class='quest'>[지배자 라키오라 (테스트)]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_RAKIORA_STORY:quest}/gi, "<span class='quest'>[A Ruler's Refuge]</span>")
		NewBattles = NewBattles.replace(/{QUEST_CRESCENT_ZAKARUM:quest}/gi, "<span class='quest'>[Earth Shaker]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT:quest}/gi, "<span class='quest'>[Twilight Desert]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_03:quest}/gi, "<span class='quest'>[Desert Passage]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_04:quest}/gi, "<span class='quest'>[Cave of the Reaper]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_05:quest}/gi, "<span class='quest'>[Voices in the Dark]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_06:quest}/gi, "<span class='quest'>[The Way Home]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_07:quest}/gi, "<span class='quest'>[Endless Questions]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_08:quest}/gi, "<span class='quest'>[Underground City]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_09:quest}/gi, "<span class='quest'>[Memory of the Past]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_10:quest}/gi, "<span class='quest'>[The Last Meeting]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EP2_EXTRA:quest}/gi, "<span class='quest'>[Death's Shadow]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EQUAL_BAKRAM:quest}/gi, "<span class='quest'>[황혼의 사막: 심판관 바크람]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EQUAL_IKRIUM:quest}/gi, "<span class='quest'>[황혼의 사막: 이크리엄]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EQUAL_SHAMIR:quest}/gi, "<span class='quest'>[황혼의 사막: 보좌관 샤미르]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_EQUAL_ZENON:quest}/gi, "<span class='quest'>[황혼의 사막: 제논]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_HAVAN:quest}/gi, "<span class='quest'>[Guardian]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_HAVAN_EQUAL:quest}/gi, "<span class='quest'>[수호자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_ISET:quest}/gi, "<span class='quest'>[Princess of the Desert]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DESERT_ISET_EQUAL:quest}/gi, "<span class='quest'>[사막의 공주]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ANCIENT_BUGEIKLOTH:quest}/gi, "<span class='quest'>[Guardian of the West]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ANCIENT_BUGEIKLOTH_EVENT:quest}/gi, "<span class='quest'>[왼편 수호자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ANCIENT_ELCULOUS:quest}/gi, "<span class='quest'>[The God of Fomors]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ANCIENT_ELCULOUS_EVENT:quest}/gi, "<span class='quest'>[마족의 신]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ANCIENT_ELCULOUS_TEST:quest}/gi, "<span class='quest'>[마족의 신 테스트]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ANCIENT_SIGLINT:quest}/gi, "<span class='quest'>[Guardian of the East]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ANCIENT_SIGLINT_EVENT:quest}/gi, "<span class='quest'>[오른편 수호자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_BUGEIKLOTH:quest}/gi, "<span class='quest'>[Frostborn Seal]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_BUGEIKLOTH_EQUAL:quest}/gi, "<span class='quest'>[봉인]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ELCULOUS:quest}/gi, "<span class='quest'>[Timeless Rage]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_ELCULOUS_EQUAL:quest}/gi, "<span class='quest'>[시간의 수호자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_SIGLINT:quest}/gi, "<span class='quest'>[Earthborn Seal]</span>")
		NewBattles = NewBattles.replace(/{QUEST_DRAGON_SIGLINT_EQUAL:quest}/gi, "<span class='quest'>[씰 키퍼]</span>")
		NewBattles = NewBattles.replace(/{QUEST_E3_EVENT_2010:quest}/gi, "<span class='quest'>[Decisive Battle]</span>")
		NewBattles = NewBattles.replace(/{QUEST_ELITE_BOSS_STAGE1:quest}/gi, "<span class='quest'>[Perilous Ruins Gauntlet]</span>")
		NewBattles = NewBattles.replace(/{QUEST_ELITE_BOSS_STAGE2:quest}/gi, "<span class='quest'>[Hoarfrost Hollow Gauntlet]</span>")
		NewBattles = NewBattles.replace(/{QUEST_ELITE_BOSS_STAGE3:quest}/gi, "<span class='quest'>[Ainle Gauntlet]</span>")
		NewBattles = NewBattles.replace(/{QUEST_ELITE_BOSS_STAGE4:quest}/gi, "<span class='quest'>[Ruins of Sanctity Gauntlet]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHILD:quest}/gi, "<span class='quest'>[A Toad on the Playground]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHILD_PET:quest}/gi, "<span class='quest'>[아이들의 놀이터]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHILD2012_ENUS:quest}/gi, "<span class='quest'>[The Toad Strikes Back]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHRISTMAS_2011_KOKR:quest}/gi, "<span class='quest'>[크리스마스 선물을 지켜라!]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHRISTMAS_2011_OVERSEA:quest}/gi, "<span class='quest'>[Defend the Goodies!]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHRISTMAS_2012_ENUS:quest}/gi, "<span class='quest'>[Ye Olde Christmas Energy]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHRISTMAS_2012_RUDOLF:quest}/gi, "<span class='quest'>[Missing Cake]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHRISTMAS_2012_SANTA:quest}/gi, "<span class='quest'>[Gift Delivery]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_CHRISTMAS_2013_KOKR:quest}/gi, "<span class='quest'>[산타의 선물을 지켜라!]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_FOOLSDAY_2016:quest}/gi, "<span class='quest'>[Kobold the Liar]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_HALLOWEEN:quest}/gi, "<span class='quest'>[Two Pumpkins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_HALLOWEEN_2012_GREEN:quest}/gi, "<span class='quest'>[Human Mimicry]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_HALLOWEEN_2012_RED:quest}/gi, "<span class='quest'>[The Walking Pumpkin]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_HALLOWEEN_2012_YELLOW:quest}/gi, "<span class='quest'>[Pumpkin Dreams]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_HALLOWEEN_DREAM_2014:quest}/gi, "<span class='quest'>[A Midfall Night's Dream]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_KONG:quest}/gi, "<span class='quest'>[두 개의 박]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_MAYBALL_2012:quest}/gi, "<span class='quest'>[쿠키가 들어있는 박]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_NEWYEAR_2014:quest}/gi, "<span class='quest'>[쫄깃쫄깃 맛좋은 떡]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_NOBLESS_CHRISTMAS_2014_KOKR:quest}/gi, "<span class='quest'>[Santa's Gift]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_NOBLESS_NEWYEAR_2015_KOKR:quest}/gi, "<span class='quest'>[쫄깃쫄깃 맛좋은 떡]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_NOBLESS_VALENTINE_2015_KOKR:quest}/gi, "<span class='quest'>[Kidnapped Lady]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_NOBLESS_VALENTINE_2016_JAJP:quest}/gi, "<span class='quest'>[납치당한 레이디, 구출!]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_PAX_2011:quest}/gi, "<span class='quest'>[E3 2011]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_SUMMER_2011:quest}/gi, "<span class='quest'>[Goddess Statue of Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_TGS_2015:quest}/gi, "<span class='quest'>[TGS 2015]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_VALENTINE_2014:quest}/gi, "<span class='quest'>[Rescue the Kidnapped Lady!]</span>")
		NewBattles = NewBattles.replace(/{QUEST_EVENT_ZHCN_DEFENCE_2012:quest}/gi, "<span class='quest'>[춘절! 선물을 지켜라!]</span>")
		NewBattles = NewBattles.replace(/{QUEST_FISH_TEST:quest}/gi, "<span class='quest'>[For Fishing Test]</span>")
		NewBattles = NewBattles.replace(/{QUEST_FISHING_YIGNACH:quest}/gi, "<span class='quest'>[[Fishing] Ignacht River]</span>")
		NewBattles = NewBattles.replace(/{QUEST_FISHING_YIGNACH_AUTO:quest}/gi, "<span class='quest'>[Ignacht River Downstream (For Auto-Fishing)]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GIANT_SPIDER_ALL:quest}/gi, "<span class='quest'>[An Ancient Race]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GIANT_SPIDER_ALL_EVENT:quest}/gi, "<span class='quest'>[고대 종족]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GIANT_SPIDER_LAGHODESSA:quest}/gi, "<span class='quest'>[Nightmare at the Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GIANT_SPIDER_LAGHODESSA_EQUAL:quest}/gi, "<span class='quest'>[폐허 위의 악몽]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GIANT_SPIDER_NORMAL:quest}/gi, "<span class='quest'>[Hidden]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GIANT_SPIDER_NORMAL_2ST:quest}/gi, "<span class='quest'>[오동석 전투조립 과제]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GIANT_SPIDER_QUEEN:quest}/gi, "<span class='quest'>[The Weeping Queen]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GIANT_SPIDER_QUEEN_EQUAL:quest}/gi, "<span class='quest'>[갈망의 여왕]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GLASGAVELEN_BRANDSHOP:quest}/gi, "<span class='quest'>[파괴의 화신 (브랜드샵)]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GLASGAVELEN_GENERAL:quest}/gi, "<span class='quest'>[Avatar of Destruction]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GLASGAVELEN_GENERAL_EQUAL:quest}/gi, "<span class='quest'>[파괴의 화신]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_AMBERMANE:quest}/gi, "<span class='quest'>[Gold Leather]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_BLACKBREEZE:quest}/gi, "<span class='quest'>[Trampled Plains]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_BLACKBREEZE_EQUAL:quest}/gi, "<span class='quest'>[짓밟힌 초원]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_CHIEFTAIN:quest}/gi, "<span class='quest'>[Decisive Battle]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_CHIEFTAIN_RAID:quest}/gi, "<span class='quest'>[Red Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_CHIEFTAIN_RAID_EQUAL:quest}/gi, "<span class='quest'>[붉은 폐허]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_DIMGRAY:quest}/gi, "<span class='quest'>[Prairie Gnoll]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_NINEFINGER:quest}/gi, "<span class='quest'>[Prairie Entrance]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_RAMPAGE:quest}/gi, "<span class='quest'>[Ruins of Sanctity]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_REDSENTINEL:quest}/gi, "<span class='quest'>[Red Archer]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SCARREDBLACK:quest}/gi, "<span class='quest'>[Gnoll King, Ruler of the Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SCARREDBLACK_EQUAL:quest}/gi, "<span class='quest'>[놀의 왕, 폐허의 패자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SCARREDBLACK_STRONG:quest}/gi, "<span class='quest'>[The Fleeing Gnoll King]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SCARREDBLACK_STRONG_EQUAL:quest}/gi, "<span class='quest'>[놀의 왕, 도망자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SCOUT:quest}/gi, "<span class='quest'>[[Practice] Patrol Mission]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SHADOWFANG:quest}/gi, "<span class='quest'>[Fomorian Emblem]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SHARPTOOTH:quest}/gi, "<span class='quest'>[Revenge]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SINGLESHOT:quest}/gi, "<span class='quest'>[Hunter at the Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_SNOWSKIN:quest}/gi, "<span class='quest'>[Gwynn's Request]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_TRIAL:quest}/gi, "<span class='quest'>[Ruins Demo Quest]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_VETERAN100:quest}/gi, "<span class='quest'>[Gnoll Assembly Area]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_WATCHMAN:quest}/gi, "<span class='quest'>[Mercenary Training Site]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GNOLL_WINTERCLAW:quest}/gi, "<span class='quest'>[Wind Through The Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_ASSISTANT:quest}/gi, "<span class='quest'>[Storeroom]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_EXTRA_JAGURSH:quest}/gi, "<span class='quest'>[Reinforcements]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_EXTRA_JAGURSH_EQUAL:quest}/gi, "<span class='quest'>[지원 요청]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_EXTRA_KAKRISH:quest}/gi, "<span class='quest'>[The Last Fragment]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_EXTRA_KAKRISH_EQUAL:quest}/gi, "<span class='quest'>[마지막 조각]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_EXTRA_KANJEL:quest}/gi, "<span class='quest'>[The Investigation]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_EXTRA_KANJEL_EQUAL:quest}/gi, "<span class='quest'>[조사]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_EXTRA_PROMPUSH:quest}/gi, "<span class='quest'>[Another Storeroom]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_EXTRA_PROMPUSH_EQUAL:quest}/gi, "<span class='quest'>[또 다른 저장고]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_HEADSERVANT:quest}/gi, "<span class='quest'>[Ellis's Trust]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_HOB:quest}/gi, "<span class='quest'>[Chicanery]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_JAGURSH:quest}/gi, "<span class='quest'>[Rocky Wilderness]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_KAKRISH:quest}/gi, "<span class='quest'>[Lost Road]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_KAKRISH_EQUAL:quest}/gi, "<span class='quest'>[찾을 수 없는 길]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_KAKRISH_GUNNER:quest}/gi, "<span class='quest'>[For Test]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_KALISH:quest}/gi, "<span class='quest'>[Hell Beyond the Door]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_KANJEL:quest}/gi, "<span class='quest'>[Herb Lands]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_KANJEL_EQUAL:quest}/gi, "<span class='quest'>[약초가 자라는 땅]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_LARKEN:quest}/gi, "<span class='quest'>[The Contract]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_LARKEN_EQUAL:quest}/gi, "<span class='quest'>[계약자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_PROMPUSH:quest}/gi, "<span class='quest'>[Contact]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_ROPEREM:quest}/gi, "<span class='quest'>[Gatekeeper of the Catacombs]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_RUSH:quest}/gi, "<span class='quest'>[Wake Up Call]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_SERVANT_LEADER:quest}/gi, "<span class='quest'>[A Town Engulfed]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOBLIN_STRAY_SERVANT:quest}/gi, "<span class='quest'>[Remnants]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOLEM_AHGLAN:quest}/gi, "<span class='quest'>[Ahglan the Golem]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOLEM_AHGLAN_EQUAL:quest}/gi, "<span class='quest'>[골렘 아글란]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOLEM_COLRU:quest}/gi, "<span class='quest'>[Colru the Golem]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GOLEM_COLRU_EQUAL:quest}/gi, "<span class='quest'>[파편 골렘]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GREMLIN_FLAMME:quest}/gi, "<span class='quest'>[The Secret]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GREMLIN_ROCKTUNE:quest}/gi, "<span class='quest'>[Rocktune's Cabin]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GREMLIN_STING:quest}/gi, "<span class='quest'>[Bandits]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GREMLIN_VENOM:quest}/gi, "<span class='quest'>[Gremlin Lair]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GREMLIN_VENOM_EQUAL:quest}/gi, "<span class='quest'>[그렘린 군락지 (테스트)]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GREMLIN_WILLY:quest}/gi, "<span class='quest'>[Cadet's Challenge]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GSTAR2008_CHIEFTAIN:quest}/gi, "<span class='quest'>[Decisive Battle 2008]</span>")
		NewBattles = NewBattles.replace(/{QUEST_GSTAR2008_PROLOGUE:quest}/gi, "<span class='quest'>[Prologue 2008]</span>")
		NewBattles = NewBattles.replace(/{QUEST_HARDCORE_DUNGEON_01:quest}/gi, "<span class='quest'>[Queen of the Cursed]</span>")
		NewBattles = NewBattles.replace(/{QUEST_HARDCORE_DUNGEON_02:quest}/gi, "<span class='quest'>[Refuge of the Dead]</span>")
		NewBattles = NewBattles.replace(/{QUEST_HARDCORE_DUNGEON_03:quest}/gi, "<span class='quest'>[Requiem of the Lost One]</span>")
		NewBattles = NewBattles.replace(/{QUEST_HUNT_KUKUS:quest}/gi, "<span class='quest'>[Kukus Plains]</span>")
		NewBattles = NewBattles.replace(/{QUEST_INFINITE_EP1:quest}/gi, "<span class='quest'>[Infinite Dungeon, Perilous Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KADAN_GENERAL:quest}/gi, "<span class='quest'>[Fate and Destiny]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KADAN_GENERAL_EQUAL:quest}/gi, "<span class='quest'>[시작된 운명]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_ALL:quest}/gi, "<span class='quest'>[Prepare for Counterattack]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_ALL2:quest}/gi, "<span class='quest'>[Proof of Courage]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_CALM:quest}/gi, "<span class='quest'>[Madness]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_CALM_EQUAL:quest}/gi, "<span class='quest'>[광란]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_CHILL:quest}/gi, "<span class='quest'>[The Howling Soul]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_CHILL_EQUAL:quest}/gi, "<span class='quest'>[울부짖는 영혼]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_COWARD:quest}/gi, "<span class='quest'>[Ocean Scent]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_COWARD_EQUAL:quest}/gi, "<span class='quest'>[바다 향기]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_CRITIC:quest}/gi, "<span class='quest'>[Snowman Alert]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_DEXTERITY:quest}/gi, "<span class='quest'>[Windgun]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_ELEGANCE:quest}/gi, "<span class='quest'>[Unfinished Business]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_FRISKY:quest}/gi, "<span class='quest'>[Western Ice Passage]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_FRISKY_ALL:quest}/gi, "<span class='quest'>[Source of the Rumor]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_FRISKY_BIGBROTHER:quest}/gi, "<span class='quest'>[Final Slingshot]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_FRISKY_BROTHER:quest}/gi, "<span class='quest'>[Another Slingshot]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_GLOOMY:quest}/gi, "<span class='quest'>[Spider Overload]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_HARD:quest}/gi, "<span class='quest'>[Kobold Chief]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_HEALTHY:quest}/gi, "<span class='quest'>[Brynn's Research]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_HEROIC:quest}/gi, "<span class='quest'>[Patrolling the Depths]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_MYSTERIOUS:quest}/gi, "<span class='quest'>[Hoarfrost Hollow in Flames]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_NIMBLE:quest}/gi, "<span class='quest'>[Fomorian Order]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_RAGE:quest}/gi, "<span class='quest'>[Greedy Kobold]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_SMART:quest}/gi, "<span class='quest'>[Hoarfrost Hollow]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_SMART_STRONG:quest}/gi, "<span class='quest'>[Southern Rock Cliff]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_STRONG:quest}/gi, "<span class='quest'>[Culprit Behind the Disturbance]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_TRIAL:quest}/gi, "<span class='quest'>[Hoarfrost Hollow Demo Quest]</span>")
		NewBattles = NewBattles.replace(/{QUEST_KOBOLD_WARM:quest}/gi, "<span class='quest'>[Appearance of a Small Bear]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LINOTOSS_GENERAL:quest}/gi, "<span class='quest'>[The Evil One]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LINOTOSS_GENERAL_EQUAL:quest}/gi, "<span class='quest'>[파멸의 마수]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_CHIULIN:quest}/gi, "<span class='quest'>[What the Dead Leave Behind]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_CHIULIN_EQUAL:quest}/gi, "<span class='quest'>[죽은 자가 남기는 것]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_EKINAR:quest}/gi, "<span class='quest'>[Give a Beggar a Coin...]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_EKINAR_EQUAL:quest}/gi, "<span class='quest'>[닿지 않는 손]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_EKINAR2:quest}/gi, "<span class='quest'>[Secret Waterway]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_GARWAY:quest}/gi, "<span class='quest'>[Pretty Green Beetle]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_INGKARA:quest}/gi, "<span class='quest'>[Taking Initiative]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_INGKARA_EQUAL:quest}/gi, "<span class='quest'>[개별 조사]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_KAZGULAM:quest}/gi, "<span class='quest'>[Ambush]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_KESER:quest}/gi, "<span class='quest'>[Where the Road Leads]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_KESER_EQUAL:quest}/gi, "<span class='quest'>[이어져 있는 길]</span>")
		NewBattles = NewBattles.replace(/{QUEST_LIZARDMAN_KIRIKAM:quest}/gi, "<span class='quest'>[Where the Sun Don't Shine]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MANKIND_CLOYAN:quest}/gi, "<span class='quest'>[The Inverse Blade]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MANKIND_CLOYAN_EQUAL:quest}/gi, "<span class='quest'>[역날의 검]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MANKIND_INGKELLS:quest}/gi, "<span class='quest'>[The Central Garden]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MANKIND_INGKELLS_EQUAL:quest}/gi, "<span class='quest'>[중앙 정원]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MANKIND_SILBERIN:quest}/gi, "<span class='quest'>[Silent Blade]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MANKIND_SILBERIN_EQUAL:quest}/gi, "<span class='quest'>[적막의 칼날]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MARIONETTE_SUCCUBUS:quest}/gi, "<span class='quest'>[Secret Naughty Chamber]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MINIGAME_JAVELIN:quest}/gi, "<span class='quest'>[투창의 달인]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MINIGAME_WALL:quest}/gi, "<span class='quest'>[벽의 달인]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN:quest}/gi, "<span class='quest'>[Misty Summit]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_BARK_MK1:quest}/gi, "<span class='quest'>[The Pinnacle]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_01:quest}/gi, "<span class='quest'>[No Man's Mine]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_02:quest}/gi, "<span class='quest'>[Crumbling Mine]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_03:quest}/gi, "<span class='quest'>[Artifical Men]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_04:quest}/gi, "<span class='quest'>[Cliff Crystal]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_05:quest}/gi, "<span class='quest'>[Under the Moonlight]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_06:quest}/gi, "<span class='quest'>[Just to be Sure]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_07:quest}/gi, "<span class='quest'>[Mine Rendezvous]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_08:quest}/gi, "<span class='quest'>[The Vanishing Magician]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_09:quest}/gi, "<span class='quest'>[A Conversation]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_10:quest}/gi, "<span class='quest'>[Bizarre Machine]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EP3_11:quest}/gi, "<span class='quest'>[Into the Abyss]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EQUAL_BENZI:quest}/gi, "<span class='quest'>[안개 봉우리: 장전의 달인 세이라]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EQUAL_CHINO:quest}/gi, "<span class='quest'>[안개 봉우리: 광기의 마사카]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EQUAL_MARKAN:quest}/gi, "<span class='quest'>[안개 봉우리: 수석조수 마르칸]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_EQUAL_VENUKAN:quest}/gi, "<span class='quest'>[안개 봉우리: 상급기사 베누칸]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_JUGGERNAUT:quest}/gi, "<span class='quest'>[The Deep Mines]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_NIGHT:quest}/gi, "<span class='quest'>[Moonlight Peak]</span>")
		NewBattles = NewBattles.replace(/{QUEST_MOUNTAIN_NIGHT_EQUAL_MUSPELL:quest}/gi, "<span class='quest'>[달빛 봉우리: 강철의 무스펠]</span>")
		NewBattles = NewBattles.replace(/{QUEST_NAUCHES_TEST:quest}/gi, "<span class='quest'>[Relic Exploration]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_BLACKHAMMER:quest}/gi, "<span class='quest'>[Rescue]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_BLACKHAMMER_EQUAL:quest}/gi, "<span class='quest'>[구출]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_BLOODFIST:quest}/gi, "<span class='quest'>[Colhen in Flames]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_BLOODFIST_EQUAL:quest}/gi, "<span class='quest'>[불타는 콜헨]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_CENTURION:quest}/gi, "<span class='quest'>[Buried Sorrow]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_CENTURION_EQUAL:quest}/gi, "<span class='quest'>[슬픔이 묻힌 곳]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_JIRKAL:quest}/gi, "<span class='quest'>[Fruitful]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_JIRKAL_EQUAL:quest}/gi, "<span class='quest'>[열매가 맺히는 나무]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_RAGE:quest}/gi, "<span class='quest'>[Pursuit]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_RIDDEN:quest}/gi, "<span class='quest'>[Betrayal]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_RIDDEN_EQUAL:quest}/gi, "<span class='quest'>[배신]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_SHAKAL:quest}/gi, "<span class='quest'>[The Fomorian Leader]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_SHAKAL_EQUAL:quest}/gi, "<span class='quest'>[마족의 우두머리]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_TITAN:quest}/gi, "<span class='quest'>[The Giant]</span>")
		NewBattles = NewBattles.replace(/{QUEST_OGRE_TITAN_EQUAL:quest}/gi, "<span class='quest'>[거대 오거]</span>")
		NewBattles = NewBattles.replace(/{QUEST_PVP_MMATCH:quest}/gi, "<span class='quest'>[Boss Brawl]</span>")
		NewBattles = NewBattles.replace(/{QUEST_PVP_PMATCH:quest}/gi, "<span class='quest'>[Capture the Relic]</span>")
		NewBattles = NewBattles.replace(/{QUEST_PVP_QUEST:quest}/gi, "<span class='quest'>[Duel Test]</span>")
		NewBattles = NewBattles.replace(/{QUEST_PVP_SPORTSDAY_FRUITCRUSH:quest}/gi, "<span class='quest'>[Sports Day Fruit Fight]</span>")
		NewBattles = NewBattles.replace(/{QUEST_PVP_SPORTSDAY_HALLOWEEN:quest}/gi, "<span class='quest'>[Halloween: Pumpkin Smashing]</span>")
		NewBattles = NewBattles.replace(/{QUEST_PVP_SPORTSDAY_SUMMERNIGHT:quest}/gi, "<span class='quest'>[여름파티 : 과일 깨기]</span>")
		NewBattles = NewBattles.replace(/{QUEST_RATMAN_KERKER:quest}/gi, "<span class='quest'>[Wet, Dark, and Mossy]</span>")
		NewBattles = NewBattles.replace(/{QUEST_RATMAN_KICHKICH:quest}/gi, "<span class='quest'>[Strong Drink]</span>")
		NewBattles = NewBattles.replace(/{QUEST_RATMAN_RAKRAK:quest}/gi, "<span class='quest'>[Sewers]</span>")
		NewBattles = NewBattles.replace(/{QUEST_RESENLIAN:quest}/gi, "<span class='quest'>[Resenlian's Labyrinth]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S2EP2_TEST_MINICAVE:quest}/gi, "<span class='quest'>[지하던전]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S2EP2_TEST_RATMAN:quest}/gi, "<span class='quest'>[랫맨 테스트]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP0_MEER:quest}/gi, "<span class='quest'>[Rocheste by Sea]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP0_MEER_EQUAL:quest}/gi, "<span class='quest'>[로체스트의 침입자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP0_STORY01:quest}/gi, "<span class='quest'>[Traces of Battle]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_01:quest}/gi, "<span class='quest'>[Autumn Reed Bed]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_02:quest}/gi, "<span class='quest'>[Deciduous Forest]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_03:quest}/gi, "<span class='quest'>[Glowing Plant]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_04:quest}/gi, "<span class='quest'>[Garden Guardian]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_05:quest}/gi, "<span class='quest'>[Corrupted Queen]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_REGINA:quest}/gi, "<span class='quest'>[Garden of Tears]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_REGINA_EQUAL:quest}/gi, "<span class='quest'>[눈물의 화원]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_WOODENELF_FREE_BATTLE:quest}/gi, "<span class='quest'>[Ben Chenner Entrance]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP1_WOODENELF_FREE_BATTLE_EQUAL:quest}/gi, "<span class='quest'>[벤 체너 초입: 칼리두스]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_01:quest}/gi, "<span class='quest'>[Orders from Above]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_02:quest}/gi, "<span class='quest'>[A Friend Once Lost]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_03:quest}/gi, "<span class='quest'>[River on Fire]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_04:quest}/gi, "<span class='quest'>[The Fallen Guardian]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_05:quest}/gi, "<span class='quest'>[Twists in Time]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_BRAHA:quest}/gi, "<span class='quest'>[Island Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_BRAHA_EQUAL:quest}/gi, "<span class='quest'>[섬 안의 유적 (테스트)]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_WOODENELF_FREE_BATTLE:quest}/gi, "<span class='quest'>[Ben Chenner Trailhead]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP2_WOODENELF_FREE_BATTLE_EQUAL:quest}/gi, "<span class='quest'>[벤 체너 기슭: 아카두스]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP3_01:quest}/gi, "<span class='quest'>[Summoning Remnant]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP3_02:quest}/gi, "<span class='quest'>[Light and Shadows]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP3_ANCIENT_GLASGAVELEN:quest}/gi, "<span class='quest'>[Temple of the Fallen Moon]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP3_ANCIENT_GLASGAVELEN_EQUAL:quest}/gi, "<span class='quest'>[달빛이 내리는 신전]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP4_01:quest}/gi, "<span class='quest'>[En Route]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP4_02:quest}/gi, "<span class='quest'>[A Place of Loss]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP4_03:quest}/gi, "<span class='quest'>[Statue at the Summit]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP4_04:quest}/gi, "<span class='quest'>[Shining Lugh]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP4_LUGHLAMHFADA:quest}/gi, "<span class='quest'>[Radiance]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP4_LUGHLAMHFADA_EQUAL:quest}/gi, "<span class='quest'>[빛나는 자]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP4_WOODENELF_FREE_BATTLE:quest}/gi, "<span class='quest'>[Ben Chenner Summit]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP4_WOODENELF_FREE_BATTLE_EQUAL:quest}/gi, "<span class='quest'>[벤 체너 정상: 크레타 카피탄]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP5_01:quest}/gi, "<span class='quest'>[Lochlann Plains Entrance]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP5_02:quest}/gi, "<span class='quest'>[Abandoned Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP5_03:quest}/gi, "<span class='quest'>[Facing the Inevitable]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP5_04:quest}/gi, "<span class='quest'>[Under the Surface]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP5_EOCHAID:quest}/gi, "<span class='quest'>[Agony and Despair]</span>")
		NewBattles = NewBattles.replace(/{QUEST_S3_EP5_MORBUS_FREE_BATTLE:quest}/gi, "<span class='quest'>[Lochlann Plains]</span>")
		NewBattles = NewBattles.replace(/{QUEST_SEASON2_TEST:quest}/gi, "<span class='quest'>[시즌2 테스트]</span>")
		NewBattles = NewBattles.replace(/{QUEST_SPIDER_SOLDIER:quest}/gi, "<span class='quest'>[The Five Spider Brothers]</span>")
		NewBattles = NewBattles.replace(/{QUEST_SPIDER_SOLDIER_RED:quest}/gi, "<span class='quest'>[Meet the Cave Spider]</span>")
		NewBattles = NewBattles.replace(/{QUEST_STRUGGLE_TOWER_PARTY:quest}/gi, "<span class='quest'>[투쟁의 탑]</span>")
		NewBattles = NewBattles.replace(/{QUEST_SUCCUBUS_SUCCUBUS:quest}/gi, "<span class='quest'>[Secret Naughty Chamber]</span>")
		NewBattles = NewBattles.replace(/{QUEST_SUCCUBUS_SUCCUBUS_EQUAL:quest}/gi, "<span class='quest'>[비밀의 방]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TEST_SOCCER:quest}/gi, "<span class='quest'>[Soccer]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOAD_GOLIATH:quest}/gi, "<span class='quest'>[Goliath]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOAD_THOR:quest}/gi, "<span class='quest'>[The Dark, Dank Sewers]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOAD_THOR_EQUAL:quest}/gi, "<span class='quest'>[으슥한 지하수로]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB:quest}/gi, "<span class='quest'>[Ship Graveyard]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_CAPTAIN:quest}/gi, "<span class='quest'>[Lost and Damned]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_COMES:quest}/gi, "<span class='quest'>[Stormy Seas]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_EP2_02:quest}/gi, "<span class='quest'>[Throw!]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_EP2_INTRO:quest}/gi, "<span class='quest'>[Buoy Hunt]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_EQUAL_CAPTAIN:quest}/gi, "<span class='quest'>[배의 무덤: 저주받은 선장]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_EQUAL_MARKIO:quest}/gi, "<span class='quest'>[배의 무덤: 후작 마르키오]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_KRAKEN:quest}/gi, "<span class='quest'>[From the Depths]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_KRAKEN_STORY:quest}/gi, "<span class='quest'>[Devil in the Water]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_MARKIO:quest}/gi, "<span class='quest'>[Tone Deaf Siren]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_MONARKA:quest}/gi, "<span class='quest'>[Treasure Hunt]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TOMB_QUEEN_EQUAL_MONARKA:quest}/gi, "<span class='quest'>[배의 무덤: 여군주 모나르카]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_FAMENU:quest}/gi, "<span class='quest'>[Habitat for Wild Plants]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_FAMENU_EQUAL:quest}/gi, "<span class='quest'>[야생식물 서식지]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_HARMA:quest}/gi, "<span class='quest'>[Investigation]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_KLAUS:quest}/gi, "<span class='quest'>[Shady Forest]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_KLAUS_EQUAL:quest}/gi, "<span class='quest'>[그늘진 숲]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_MATUR:quest}/gi, "<span class='quest'>[West Hilder Forest]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_MEPERDU:quest}/gi, "<span class='quest'>[Beginning of the Memory]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_MEPERDU_EQUAL:quest}/gi, "<span class='quest'>[시작되는 기억]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_TAONU:quest}/gi, "<span class='quest'>[Fight That Must Be Won]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_TAONU_EQUAL:quest}/gi, "<span class='quest'>[이겨야만 하는 싸움]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_ZYARGA:quest}/gi, "<span class='quest'>[Forest Ruins]</span>")
		NewBattles = NewBattles.replace(/{QUEST_TROLL_ZYARGA_EQUAL:quest}/gi, "<span class='quest'>[숲 속 유적지]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_ALMOST:quest}/gi, "<span class='quest'>[The Unveiling Truth]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_ARSON:quest}/gi, "<span class='quest'>[Burnt Pumpkin Field]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_ASH:quest}/gi, "<span class='quest'>[Friend or Foe]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_DRINKER:quest}/gi, "<span class='quest'>[Ulchas's Relic]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_DUKE:quest}/gi, "<span class='quest'>[Depths of Ainle]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_FLICKER:quest}/gi, "<span class='quest'>[Where the legend sleeps]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_GLITTER:quest}/gi, "<span class='quest'>[Regrets...Too Late]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_KNIGHT:quest}/gi, "<span class='quest'>[Being from the Other World]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_PRINCE:quest}/gi, "<span class='quest'>[Blood Prince]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_RED:quest}/gi, "<span class='quest'>[Piercing the Crescent Moon]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_RIPPER:quest}/gi, "<span class='quest'>[Dead End Street]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPIRE_TRIAL:quest}/gi, "<span class='quest'>[Ainle Demo Quest]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPLORD_EMPEROR:quest}/gi, "<span class='quest'>[Holy Ground]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPLORD_NORMAL:quest}/gi, "<span class='quest'>[Shadowed by Darkness]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VAMPLORD_NORMAL_EQUAL:quest}/gi, "<span class='quest'>[진실에 드리운 어둠]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_CROMCRUACH:quest}/gi, "<span class='quest'>[God of Death]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_CROMCRUACH_EQUAL:quest}/gi, "<span class='quest'>[죽음의 신]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_ELAHAN:quest}/gi, "<span class='quest'>[Burning Temple]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_ELAHAN_EQUAL:quest}/gi, "<span class='quest'>[불타는 신전]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_EP4_02:quest}/gi, "<span class='quest'>[Into the Abyss]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_LAVASAT:quest}/gi, "<span class='quest'>[Gates of Hell]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_LAVASAT_EQUAL:quest}/gi, "<span class='quest'>[저승을 지키는 문지기]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_YULKES:quest}/gi, "<span class='quest'>[Desolate Malina]</span>")
		NewBattles = NewBattles.replace(/{QUEST_VOLCANO_YULKES_EQUAL:quest}/gi, "<span class='quest'>[황폐한 모르반]</span>")
		NewBattles = NewBattles.replace(/{QUEST_WISP_TWIN:quest}/gi, "<span class='quest'>[Two Moons]</span>")
		NewBattles = NewBattles.replace(/{QUEST_XE_TUTORIAL:quest}/gi, "<span class='quest'>[Fine Mercenary Training Site]</span>")
		NewBattles = NewBattles.replace(/{QUEST_YETI_BIGHORN:quest}/gi, "<span class='quest'>[Big Horn Yeti]</span>")
		NewBattles = NewBattles.replace(/{QUEST_YETI_BIGHORN_EQUAL:quest}/gi, "<span class='quest'>[큰 뿔 예티]</span>")
		NewBattles = NewBattles.replace(/{QUEST_YETI_BLACKVALLEY:quest}/gi, "<span class='quest'>[Revived Fear]</span>")
		NewBattles = NewBattles.replace(/{QUEST_YETI_BLACKVALLEY_EQUAL:quest}/gi, "<span class='quest'>[되살아난 공포]</span>")
		NewBattles = NewBattles.replace(/{QUEST_YETI_ROCKJAW:quest}/gi, "<span class='quest'>[Yeti King]</span>")
		NewBattles = NewBattles.replace(/{QUEST_YETI_ROCKJAW_EQUAL:quest}/gi, "<span class='quest'>[예티의 왕]</span>")
		NewBattles = NewBattles.replace(/{QUEST_YETI_SARGAMU:quest}/gi, "<span class='quest'>[The Yeti, an Ancient Race]</span>")
$(this).html(NewBattles)
})
}