ReplaceTask = function (){
$('.storygoal').each(function() {
		NewTask = $(this).html();
		NewTask = NewTask.replace(/{AHIR:npc}/gi, "<span class='npc'>[Asher]</span>")
		NewTask = NewTask.replace(/{AIDAN:npc}/gi, "<span class='npc'>[Aodhan]</span>")
		NewTask = NewTask.replace(/{AILIE:npc}/gi, "<span class='npc'>[Aislinn]</span>")
		NewTask = NewTask.replace(/{AKADUS:npc}/gi, "<span class='npc'>[Akadus]</span>")
		NewTask = NewTask.replace(/{ALADIN:npc}/gi, "<span class='npc'>[알라딘]</span>")
		NewTask = NewTask.replace(/{ALELE:npc}/gi, "<span class='npc'>[Errol]</span>")
		NewTask = NewTask.replace(/{ALIBABA:npc}/gi, "<span class='npc'>[알리바바]</span>")
		NewTask = NewTask.replace(/{ALICE:npc}/gi, "<span class='npc'>[Ellis]</span>")
		NewTask = NewTask.replace(/{ANNEST:npc}/gi, "<span class='npc'>[Shayla]</span>")
		NewTask = NewTask.replace(/{ARIAL:npc}/gi, "<span class='npc'>[Arielle]</span>")
		NewTask = NewTask.replace(/{ARTHYEN:npc}/gi, "<span class='npc'>[Arthyen]</span>")
		NewTask = NewTask.replace(/{ARTHYEN2:npc}/gi, "<span class='npc'>[Arthyen]</span>")
		NewTask = NewTask.replace(/{BARAX:npc}/gi, "<span class='npc'>[Brakis]</span>")
		NewTask = NewTask.replace(/{BEAUTYCAT:npc}/gi, "<span class='npc'>[Kayna]</span>")
		NewTask = NewTask.replace(/{BEAUTYCAT_MORVAN:npc}/gi, "<span class='npc'>[Lubber]</span>")
		NewTask = NewTask.replace(/{BEAUTYCAT_ROCHEST:npc}/gi, "<span class='npc'>[Louie the Cat]</span>")
		NewTask = NewTask.replace(/{BEGGAR:npc}/gi, "<span class='npc'>[Beggar]</span>")
		NewTask = NewTask.replace(/{BITHEK:npc}/gi, "<span class='npc'>[Videk]</span>")
		NewTask = NewTask.replace(/{BITHEK_EP4:npc}/gi, "<span class='npc'>[Videk]</span>")
		NewTask = NewTask.replace(/{BITHEK_MAGIC:npc}/gi, "<span class='npc'>[Videk]</span>")
		NewTask = NewTask.replace(/{BLACKHAMMER:npc}/gi, "<span class='npc'>[Black Hammer]</span>")
		NewTask = NewTask.replace(/{BLANK:npc}/gi, "<span class='npc'>[ ]</span>")
		NewTask = NewTask.replace(/{BLANK_TEMPLE:npc}/gi, "<span class='npc'>[Temple]</span>")
		NewTask = NewTask.replace(/{BLAWIN:npc}/gi, "<span class='npc'>[Blawynn]</span>")
		NewTask = NewTask.replace(/{BOY:npc}/gi, "<span class='npc'>[Boy]</span>")
		NewTask = NewTask.replace(/{BRYN:npc}/gi, "<span class='npc'>[Brynn]</span>")
		NewTask = NewTask.replace(/{CANCLE:npc}/gi, "<span class='npc'>[CANCEL]</span>")
		NewTask = NewTask.replace(/{CARRIAGE:npc}/gi, "<span class='npc'>[Carriage]</span>")
		NewTask = NewTask.replace(/{CARRIAGE_ROCHEST:npc}/gi, "<span class='npc'>[Carriage Driver]</span>")
		NewTask = NewTask.replace(/{CARYL:npc}/gi, "<span class='npc'>[Caryl]</span>")
		NewTask = NewTask.replace(/{CEARA:npc}/gi, "<span class='npc'>[Ceara]</span>")
		NewTask = NewTask.replace(/{CETHE:npc}/gi, "<span class='npc'>[Cethe]</span>")
		NewTask = NewTask.replace(/{CICHOL:npc}/gi, "<span class='npc'>[Cichol]</span>")
		NewTask = NewTask.replace(/{CICHOL_ILLUSION:npc}/gi, "<span class='npc'>[Cichol's Projection]</span>")
		NewTask = NewTask.replace(/{CLODAGH:npc}/gi, "<span class='npc'>[Clodagh]</span>")
		NewTask = NewTask.replace(/{COMPANION_CUBE:npc}/gi, "<span class='npc'>[Voice of GLaDOS]</span>")
		NewTask = NewTask.replace(/{CRYSTAL:npc}/gi, "<span class='npc'>[Crystal]</span>")
		NewTask = NewTask.replace(/{DAL_KOTORI:npc}/gi, "<span class='npc'>[코토리]</span>")
		NewTask = NewTask.replace(/{DAL_KOTORI2:npc}/gi, "<span class='npc'>[코토리]</span>")
		NewTask = NewTask.replace(/{DAL_KURUMI:npc}/gi, "<span class='npc'>[쿠루미]</span>")
		NewTask = NewTask.replace(/{DAL_REINE:npc}/gi, "<span class='npc'>[레이네]</span>")
		NewTask = NewTask.replace(/{DAL_REINE2:npc}/gi, "<span class='npc'>[레이네]</span>")
		NewTask = NewTask.replace(/{DAL_TOKHA:npc}/gi, "<span class='npc'>[토카]</span>")
		NewTask = NewTask.replace(/{DAL_TOKHA2:npc}/gi, "<span class='npc'>[토카]</span>")
		NewTask = NewTask.replace(/{DANARYN:npc}/gi, "<span class='npc'>[Danaryn]</span>")
		NewTask = NewTask.replace(/{DENARU:npc}/gi, "<span class='npc'>[Deniz]</span>")
		NewTask = NewTask.replace(/{DEV:npc}/gi, "<span class='npc'>[Papathingh]</span>")
		NewTask = NewTask.replace(/{DIANANN:npc}/gi, "<span class='npc'>[Dianann]</span>")
		NewTask = NewTask.replace(/{DOLORES:npc}/gi, "<span class='npc'>[Dolores]</span>")
		NewTask = NewTask.replace(/{DWYN:npc}/gi, "<span class='npc'>[Gwynn]</span>")
		NewTask = NewTask.replace(/{DWYN_ROCHEST:npc}/gi, "<span class='npc'>[Gwynn]</span>")
		NewTask = NewTask.replace(/{DYEING:npc}/gi, "<span class='npc'>[Dye]</span>")
		NewTask = NewTask.replace(/{EASTER_BUNNY:npc}/gi, "<span class='npc'>[Easter Bunny]</span>")
		NewTask = NewTask.replace(/{EGOFEATER:npc}/gi, "<span class='npc'>[Ego Feather]</span>")
		NewTask = NewTask.replace(/{EIRE:npc}/gi, "<span class='npc'>[Allysse]</span>")
		NewTask = NewTask.replace(/{ELAHAN:npc}/gi, "<span class='npc'>[Enzo]</span>")
		NewTask = NewTask.replace(/{ELAINE:npc}/gi, "<span class='npc'>[Elaine]</span>")
		NewTask = NewTask.replace(/{EMMA:npc}/gi, "<span class='npc'>[Emma]</span>")
		NewTask = NewTask.replace(/{ENCHANT:npc}/gi, "<span class='npc'>[Enchant]</span>")
		NewTask = NewTask.replace(/{END_FUNC:npc}/gi, "<span class='npc'>[End]</span>")
		NewTask = NewTask.replace(/{END_TALK:npc}/gi, "<span class='npc'>[End Conversation]</span>")
		NewTask = NewTask.replace(/{ERINBOOK:npc}/gi, "<span class='npc'>[Paradise Chronicles]</span>")
		NewTask = NewTask.replace(/{ERNMASS:npc}/gi, "<span class='npc'>[Ernmass]</span>")
		NewTask = NewTask.replace(/{ESYLLT:npc}/gi, "<span class='npc'>[Esyllt]</span>")
		NewTask = NewTask.replace(/{FAILINIS:npc}/gi, "<span class='npc'>[Finnec]</span>")
		NewTask = NewTask.replace(/{FAIRYTAIL_ELSA:npc}/gi, "<span class='npc'>[엘자]</span>")
		NewTask = NewTask.replace(/{FAIRYTAIL_GRAY:npc}/gi, "<span class='npc'>[그레이]</span>")
		NewTask = NewTask.replace(/{FAIRYTAIL_LUCY:npc}/gi, "<span class='npc'>[루시]</span>")
		NewTask = NewTask.replace(/{FAIRYTAIL_MAKAROV:npc}/gi, "<span class='npc'>[마카로프]</span>")
		NewTask = NewTask.replace(/{FAIRYTAIL_NATSU:npc}/gi, "<span class='npc'>[나츠]</span>")
		NewTask = NewTask.replace(/{FENELLA:npc}/gi, "<span class='npc'>[Fenella]</span>")
		NewTask = NewTask.replace(/{FERGHUS:npc}/gi, "<span class='npc'>[Ferghus]</span>")
		NewTask = NewTask.replace(/{FERRY:npc}/gi, "<span class='npc'>[Ferryman]</span>")
		NewTask = NewTask.replace(/{FERRY_COLHEN:npc}/gi, "<span class='npc'>[Malina Ferryman]</span>")
		NewTask = NewTask.replace(/{FERRY_MORVAN:npc}/gi, "<span class='npc'>[Boatman]</span>")
		NewTask = NewTask.replace(/{FISHCAT:npc}/gi, "<span class='npc'>[Shire]</span>")
		NewTask = NewTask.replace(/{FLASHBACK_ALTAR:npc}/gi, "<span class='npc'>[Altar of Memories]</span>")
		NewTask = NewTask.replace(/{FLOVIAN:npc}/gi, "<span class='npc'>[Flovian]</span>")
		NewTask = NewTask.replace(/{FLOVIAN_EMPTY:npc}/gi, "<span class='npc'>[Empty house?]</span>")
		NewTask = NewTask.replace(/{FOUNTAIN:npc}/gi, "<span class='npc'>[Fountain]</span>")
		NewTask = NewTask.replace(/{FYNN:npc}/gi, "<span class='npc'>[Flannery]</span>")
		NewTask = NewTask.replace(/{GEREN:npc}/gi, "<span class='npc'>[Gallagher]</span>")
		NewTask = NewTask.replace(/{GERENS1:npc}/gi, "<span class='npc'>[Gallagher]</span>")
		NewTask = NewTask.replace(/{GHOST_PUMPKIN:npc}/gi, "<span class='npc'>[Ghost Kobold Pumpkin]</span>")
		NewTask = NewTask.replace(/{GILLESPIE:npc}/gi, "<span class='npc'>[Gilliam]</span>")
		NewTask = NewTask.replace(/{GRAYMAN:npc}/gi, "<span class='npc'>[Mysterious Man]</span>")
		NewTask = NewTask.replace(/{GREEN_PUMPKIN:npc}/gi, "<span class='npc'>[The Green Pumpkin]</span>")
		NewTask = NewTask.replace(/{GRIMREAPER:npc}/gi, "<span class='npc'>[Grim Reaper]</span>")
		NewTask = NewTask.replace(/{GUY:npc}/gi, "<span class='npc'>[Young Man]</span>")
		NewTask = NewTask.replace(/{IDAHL:npc}/gi, "<span class='npc'>[Idal]</span>")
		NewTask = NewTask.replace(/{INGKELLS:npc}/gi, "<span class='npc'>[Ingkells]</span>")
		NewTask = NewTask.replace(/{ISET:npc}/gi, "<span class='npc'>[Iset]</span>")
		NewTask = NewTask.replace(/{ISET_RETURN_TALK_01:npc}/gi, "<span class='npc'>[Attack, Havan!]</span>")
		NewTask = NewTask.replace(/{ISET_RETURN_TALK_02:npc}/gi, "<span class='npc'>[Protect me, Havan!]</span>")
		NewTask = NewTask.replace(/{ISET_RETURN_TALK_03:npc}/gi, "<span class='npc'>[Destroy them all!]</span>")
		NewTask = NewTask.replace(/{ISET_RETURN_TALK_04:npc}/gi, "<span class='npc'>[I'll turn you to dust.]</span>")
		NewTask = NewTask.replace(/{ISET_RETURN_TALK_05:npc}/gi, "<span class='npc'>[Havan will give you what you deserve!]</span>")
		NewTask = NewTask.replace(/{ISET_RETURN_TALK_06:npc}/gi, "<span class='npc'>[My dear guardian, make them suffer!]</span>")
		NewTask = NewTask.replace(/{JARLATH:npc}/gi, "<span class='npc'>[Jarlath]</span>")
		NewTask = NewTask.replace(/{JOE:npc}/gi, "<span class='npc'>[Sugarcane Joe]</span>")
		NewTask = NewTask.replace(/{JUDARU:npc}/gi, "<span class='npc'>[쥬달]</span>")
		NewTask = NewTask.replace(/{KADAN:npc}/gi, "<span class='npc'>[Keaghan]</span>")
		NewTask = NewTask.replace(/{KIAHN:npc}/gi, "<span class='npc'>[Kean]</span>")
		NewTask = NewTask.replace(/{KIRSTIE:npc}/gi, "<span class='npc'>[Kirstie]</span>")
		NewTask = NewTask.replace(/{KIRUNGA:npc}/gi, "<span class='npc'>[Krunk]</span>")
		NewTask = NewTask.replace(/{KNIGHT:npc}/gi, "<span class='npc'>[Knight]</span>")
		NewTask = NewTask.replace(/{KNIGHTS:npc}/gi, "<span class='npc'>[Knights]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_01:npc}/gi, "<span class='npc'>[Marrec and Ceara are being all lovey-dovey!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_02:npc}/gi, "<span class='npc'>[That Clodagh always has the most profound thoughts!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_03:npc}/gi, "<span class='npc'>[Marrec washes his hair with his helmet on!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_04:npc}/gi, "<span class='npc'>[Aodhan is such a pansy. You could take him out with just one arrow!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_05:npc}/gi, "<span class='npc'>[Wahaha! It's a lot more fun to lie!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_06:npc}/gi, "<span class='npc'>[There's a ghost behind you!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_07:npc}/gi, "<span class='npc'>[My elderly mother is sick at home. Please, don't hurt me...]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_07_2:npc}/gi, "<span class='npc'>[I'm trying to repent for all my lies...]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_08:npc}/gi, "<span class='npc'>[Yeah, right! Man, you're gullible!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_09:npc}/gi, "<span class='npc'>[Will you turn a blind eye just this once?]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_10:npc}/gi, "<span class='npc'>[Ferghus breaks your equipments because he cares!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_11:npc}/gi, "<span class='npc'>[Only losers are clueless!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_FOOLSDAY_TALK_12:npc}/gi, "<span class='npc'>[It's coming back bigger and better than before!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_HEALTHY_LOVE_TALK_01:npc}/gi, "<span class='npc'>[Love, why do you deny me so?]</span>")
		NewTask = NewTask.replace(/{KOBOLD_HEALTHY_LOVE_TALK_02:npc}/gi, "<span class='npc'>[My love, please, stop hurting me.]</span>")
		NewTask = NewTask.replace(/{KOBOLD_HEALTHY_LOVE_TALK_03:npc}/gi, "<span class='npc'>[How can you reject me!]</span>")
		NewTask = NewTask.replace(/{KOBOLD_HEALTHY_LOVE_TALK_04:npc}/gi, "<span class='npc'>[Do not interfere with my love! ]</span>")
		NewTask = NewTask.replace(/{KOBOLD_HEALTHY_LOVE_TALK_05:npc}/gi, "<span class='npc'>[Is this the end of my love?]</span>")
		NewTask = NewTask.replace(/{KOBOLD_HEALTHY_LOVE_TALK_06:npc}/gi, "<span class='npc'>[Is this the taste of love?]</span>")
		NewTask = NewTask.replace(/{KOBOLD_HEALTHY_LOVE_TALK_07:npc}/gi, "<span class='npc'>[Betrayal hurts so much.]</span>")
		NewTask = NewTask.replace(/{LAURA:npc}/gi, "<span class='npc'>[Lora]</span>")
		NewTask = NewTask.replace(/{LAURYS:npc}/gi, "<span class='npc'>[Laurys]</span>")
		NewTask = NewTask.replace(/{LETTER:npc}/gi, "<span class='npc'>[Letter]</span>")
		NewTask = NewTask.replace(/{LOHR:npc}/gi, "<span class='npc'>[Lowell]</span>")
		NewTask = NewTask.replace(/{LOSTWINGS:npc}/gi, "<span class='npc'>[Wingless God]</span>")
		NewTask = NewTask.replace(/{LUGH:npc}/gi, "<span class='npc'>[Lugh]</span>")
		NewTask = NewTask.replace(/{LUGHLAMHFADA_TALK_FRAGARACH:npc}/gi, "<span class='npc'>[Oh, Fragarach!]</span>")
		NewTask = NewTask.replace(/{LUGHLAMHFADA_TALK_TATHLUM:npc}/gi, "<span class='npc'>[Try to endure the Tathlum blast!]</span>")
		NewTask = NewTask.replace(/{MACHA:npc}/gi, "<span class='npc'>[Macha]</span>")
		NewTask = NewTask.replace(/{MAIL_BOX:npc}/gi, "<span class='npc'>[Open Mailbox]</span>")
		NewTask = NewTask.replace(/{MAKING_CLOTH:npc}/gi, "<span class='npc'>[Tailoring]</span>")
		NewTask = NewTask.replace(/{MARREC:npc}/gi, "<span class='npc'>[Marrec]</span>")
		NewTask = NewTask.replace(/{MEER:npc}/gi, "<span class='npc'>[Muir]</span>")
		NewTask = NewTask.replace(/{MEMO:npc}/gi, "<span class='npc'>[Note]</span>")
		NewTask = NewTask.replace(/{MERCENARIES:npc}/gi, "<span class='npc'>[Mercenaries]</span>")
		NewTask = NewTask.replace(/{MERCENARY:npc}/gi, "<span class='npc'>[Mercenary]</span>")
		NewTask = NewTask.replace(/{MEVE:npc}/gi, "<span class='npc'>[Old Meb]</span>")
		NewTask = NewTask.replace(/{MILLED:npc}/gi, "<span class='npc'>[Milo]</span>")
		NewTask = NewTask.replace(/{MILLED_CRESCENT:npc}/gi, "<span class='npc'>[Miller]</span>")
		NewTask = NewTask.replace(/{MILLED_ROBE:npc}/gi, "<span class='npc'>[Milo]</span>")
		NewTask = NewTask.replace(/{MILLED_UNKNOWN:npc}/gi, "<span class='npc'>[?]</span>")
		NewTask = NewTask.replace(/{MINISHOP:npc}/gi, "<span class='npc'>[Royal Army Recruit]</span>")
		NewTask = NewTask.replace(/{MOIRA:npc}/gi, "<span class='npc'>[Simone]</span>")
		NewTask = NewTask.replace(/{MORVAN_SOLDIER:npc}/gi, "<span class='npc'>[Guard]</span>")
		NewTask = NewTask.replace(/{MORVANINN:npc}/gi, "<span class='npc'>[Inn]</span>")
		NewTask = NewTask.replace(/{MUSICIAN:npc}/gi, "<span class='npc'>[Pied Piper]</span>")
		NewTask = NewTask.replace(/{NEVEREZ:npc}/gi, "<span class='npc'>[Nyle]</span>")
		NewTask = NewTask.replace(/{NIEVE:npc}/gi, "<span class='npc'>[Nel]</span>")
		NewTask = NewTask.replace(/{NO:npc}/gi, "<span class='npc'>[NO]</span>")
		NewTask = NewTask.replace(/{NOLWENN:npc}/gi, "<span class='npc'>[Naveen]</span>")
		NewTask = NewTask.replace(/{OGRE:npc}/gi, "<span class='npc'>[Ogre]</span>")
		NewTask = NewTask.replace(/{OK:npc}/gi, "<span class='npc'>[OK]</span>")
		NewTask = NewTask.replace(/{OWL:npc}/gi, "<span class='npc'>[Mailbox]</span>")
		NewTask = NewTask.replace(/{PARROT:npc}/gi, "<span class='npc'>[Pramin]</span>")
		NewTask = NewTask.replace(/{PARROT_SUMMON:npc}/gi, "<span class='npc'>[소환된 라비]</span>")
		NewTask = NewTask.replace(/{PINK_RABBIT:npc}/gi, "<span class='npc'>[Poe the Courier]</span>")
		NewTask = NewTask.replace(/{POSTER:npc}/gi, "<span class='npc'>[Foster]</span>")
		NewTask = NewTask.replace(/{PRODUCT:npc}/gi, "<span class='npc'>[Craft]</span>")
		NewTask = NewTask.replace(/{PRODUCT_ARMOR:npc}/gi, "<span class='npc'>[Armorsmithing]</span>")
		NewTask = NewTask.replace(/{PRODUCT_METAL_WEAPON:npc}/gi, "<span class='npc'>[Weaponsmithing]</span>")
		NewTask = NewTask.replace(/{PRODUCT_SEWING:npc}/gi, "<span class='npc'>[Tailoring]</span>")
		NewTask = NewTask.replace(/{PRODUCT_WORKMANSHIP:npc}/gi, "<span class='npc'>[Goldsmithing]</span>")
		NewTask = NewTask.replace(/{QUESTION:npc}/gi, "<span class='npc'>[?]</span>")
		NewTask = NewTask.replace(/{RANKUP:npc}/gi, "<span class='npc'>[Rank Up Completed]</span>")
		NewTask = NewTask.replace(/{RAZIIKUM:npc}/gi, "<span class='npc'>[Lazkum]</span>")
		NewTask = NewTask.replace(/{RAZIIKUM_S3:npc}/gi, "<span class='npc'>[Lazkum]</span>")
		NewTask = NewTask.replace(/{RED_PUMPKIN:npc}/gi, "<span class='npc'>[The Red Pumpkin]</span>")
		NewTask = NewTask.replace(/{REIKA:npc}/gi, "<span class='npc'>[Rhea]</span>")
		NewTask = NewTask.replace(/{RESHAU:npc}/gi, "<span class='npc'>[Lechaud]</span>")
		NewTask = NewTask.replace(/{RHYS:npc}/gi, "<span class='npc'>[Rhys]</span>")
		NewTask = NewTask.replace(/{RIEL:npc}/gi, "<span class='npc'>[Reilly]</span>")
		NewTask = NewTask.replace(/{RONAUN:npc}/gi, "<span class='npc'>[Ronaun]</span>")
		NewTask = NewTask.replace(/{RUDELL:npc}/gi, "<span class='npc'>[Rudell]</span>")
		NewTask = NewTask.replace(/{RUDEREK:npc}/gi, "<span class='npc'>[Riordan]</span>")
		NewTask = NewTask.replace(/{RUDEREK_ROCHEST:npc}/gi, "<span class='npc'>[Riordan]</span>")
		NewTask = NewTask.replace(/{RUDOLF:npc}/gi, "<span class='npc'>[Big Brother Rudolph]</span>")
		NewTask = NewTask.replace(/{RUDOLF_NORMAL:npc}/gi, "<span class='npc'>[Rudolph]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_01:npc}/gi, "<span class='npc'>[How did you find me?]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_02:npc}/gi, "<span class='npc'>[My treasures!]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_03:npc}/gi, "<span class='npc'>[*Gasp* H-how could you be so f-fast?]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_04:npc}/gi, "<span class='npc'>[*Squeak*]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_05:npc}/gi, "<span class='npc'>[*Pant*]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_06:npc}/gi, "<span class='npc'>[*Pant* I-I'm so exhausted...]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_07:npc}/gi, "<span class='npc'>[You're all going to suffer!]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_08:npc}/gi, "<span class='npc'>[*Squeak* My pouch! My nest egg!]</span>")
		NewTask = NewTask.replace(/{RUNNER_RATMAN_TALK_09:npc}/gi, "<span class='npc'>[My pouch! My treasure pouch!]</span>")
		NewTask = NewTask.replace(/{S_ROBE:npc}/gi, "<span class='npc'>[Woman]</span>")
		NewTask = NewTask.replace(/{SAILOR:npc}/gi, "<span class='npc'>[Sailor]</span>")
		NewTask = NewTask.replace(/{SANTA_RATMAN:npc}/gi, "<span class='npc'>[Santa]</span>")
		NewTask = NewTask.replace(/{SAO_ASUNA:npc}/gi, "<span class='npc'>[Asuna]</span>")
		NewTask = NewTask.replace(/{SAO_KIRITO:npc}/gi, "<span class='npc'>[Kirito]</span>")
		NewTask = NewTask.replace(/{SAO_LISBET:npc}/gi, "<span class='npc'>[Lisbeth]</span>")
		NewTask = NewTask.replace(/{SEIRA:npc}/gi, "<span class='npc'>[Seira]</span>")
		NewTask = NewTask.replace(/{SEREUHA:npc}/gi, "<span class='npc'>[Seanna]</span>")
		NewTask = NewTask.replace(/{SEREUHA_MORVAN:npc}/gi, "<span class='npc'>[Seanna]</span>")
		NewTask = NewTask.replace(/{SEREUHA_ROBE:npc}/gi, "<span class='npc'>[Woman]</span>")
		NewTask = NewTask.replace(/{SHAKAL:npc}/gi, "<span class='npc'>[Shakarr]</span>")
		NewTask = NewTask.replace(/{SHALOTTE:npc}/gi, "<span class='npc'>[Cennet]</span>")
		NewTask = NewTask.replace(/{SHALOTTE_EP4:npc}/gi, "<span class='npc'>[Cennet]</span>")
		NewTask = NewTask.replace(/{SHEEP:npc}/gi, "<span class='npc'>[Hereta]</span>")
		NewTask = NewTask.replace(/{SILBERIN:npc}/gi, "<span class='npc'>[Silberin]</span>")
		NewTask = NewTask.replace(/{SKILL:npc}/gi, "<span class='npc'>[Skill Training]</span>")
		NewTask = NewTask.replace(/{SMALL_TALK:npc}/gi, "<span class='npc'>[Chitchat]</span>")
		NewTask = NewTask.replace(/{SOLDIER:npc}/gi, "<span class='npc'>[Guard]</span>")
		NewTask = NewTask.replace(/{SOLDIER_DEATHMATCH:npc}/gi, "<span class='npc'>[Battlemaster]</span>")
		NewTask = NewTask.replace(/{SOLDIER_PORT:npc}/gi, "<span class='npc'>[Dock Guard]</span>")
		NewTask = NewTask.replace(/{SOLDIER_ROCHEST:npc}/gi, "<span class='npc'>[Rocheste Castle Guard]</span>")
		NewTask = NewTask.replace(/{SOLEHR:npc}/gi, "<span class='npc'>[Solair]</span>")
		NewTask = NewTask.replace(/{STAMPSHOP:npc}/gi, "<span class='npc'>[Royal Army Recruit]</span>")
		NewTask = NewTask.replace(/{STRANGECAT:npc}/gi, "<span class='npc'>[Strange Traveler]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_01:npc}/gi, "<span class='npc'>[Come closer.]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_02:npc}/gi, "<span class='npc'>[Don't flee, my love.]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_03:npc}/gi, "<span class='npc'>[I'll go easy on you.]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_04:npc}/gi, "<span class='npc'>[Stay there. Don't move.]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_05:npc}/gi, "<span class='npc'>[I promise it won't hurt.]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_06:npc}/gi, "<span class='npc'>[Don't be nervous, darling.]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_07:npc}/gi, "<span class='npc'>[Shh, just hold still...]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_08:npc}/gi, "<span class='npc'>[You're hurting me!]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_09:npc}/gi, "<span class='npc'>[Stop it!]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_10:npc}/gi, "<span class='npc'>[How dare you!]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_11:npc}/gi, "<span class='npc'>[*moooan*]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_12:npc}/gi, "<span class='npc'>[Shall we go again?]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_13:npc}/gi, "<span class='npc'>[How...dirty.]</span>")
		NewTask = NewTask.replace(/{SUCCUBUS_SUCCUBUS_TALK_14:npc}/gi, "<span class='npc'>[I don't feel a thing.]</span>")
		NewTask = NewTask.replace(/{SUSPICIOUSCAT:npc}/gi, "<span class='npc'>[Shady Traveler]</span>")
		NewTask = NewTask.replace(/{TAMEIN:npc}/gi, "<span class='npc'>[Torrin]</span>")
		NewTask = NewTask.replace(/{THE_HEAVY:npc}/gi, "<span class='npc'>[The Heavy]</span>")
		NewTask = NewTask.replace(/{THEMAN:npc}/gi, "<span class='npc'>[Mysterious Man]</span>")
		NewTask = NewTask.replace(/{TI:npc}/gi, "<span class='npc'>[Tieve]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNA_01:npc}/gi, "<span class='npc'>[You're awake.\\nYesterday, at the Bell Tower...]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNA_02:npc}/gi, "<span class='npc'>[(Tieve looks away, her eyes full of tears.) \\nI...I didn't have the chance to thank you.]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNA_03:npc}/gi, "<span class='npc'>[It's because of you I'm even alive. And yet...]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNA_04:npc}/gi, "<span class='npc'>[(Tieve shakes her head gently)\\nNever mind that. Please, what is your name?]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNA_05:npc}/gi, "<span class='npc'>[(Tieve takes your hand and looks earnestly into your eyes.)\\n{:name}. Thank you. For yesterday.]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_01:npc}/gi, "<span class='npc'>[(Tieve lets your hand drop.)\\nI only wish I could have saved him, too...]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_02:npc}/gi, "<span class='npc'>[(You ask who she means, and she looks startled.)]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_03:npc}/gi, "<span class='npc'>[Why, the spider, of course. Who else?]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_04:npc}/gi, "<span class='npc'>[(Tieve walks toward the window and looks out.)]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_05:npc}/gi, "<span class='npc'>[He didn't mean to, you know. He's not usually like that. \\nBut he was scared. There's an evil taking hold of the land.]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_06:npc}/gi, "<span class='npc'>[I...I don't quite understand it. Yet I feel as if I should.\\n(Tieve's voice sounds pained.)]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_07:npc}/gi, "<span class='npc'>[(Tieve turns from the window.)\\nI almost forgot! You're wanted at the Mercenary Outpost.]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_08:npc}/gi, "<span class='npc'>[I have duties to perform as well. The townspeople \\nmust be rattled from yesterday. I must attend to them.]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_09:npc}/gi, "<span class='npc'>[Find Marrec at the Mercenary Outpost. He is...\\nHe is a sub-captain or assistant leader or veteran or--]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_10:npc}/gi, "<span class='npc'>[(Tieve looks overwhelmed as she tries to remember.)\\nIn any case, he is a member of the Crimson Blade mercenaries.]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_11:npc}/gi, "<span class='npc'>[Please, go find him.]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_12:npc}/gi, "<span class='npc'>[(Tieve starts to leave, but stops herself at the door.)]</span>")
		NewTask = NewTask.replace(/{TI_TALK_PROLOGUE_INNB_13:npc}/gi, "<span class='npc'>[{:name}. Whatever happens, stay safe.\\nPlease...]</span>")
		NewTask = NewTask.replace(/{TI_TEMPLE:npc}/gi, "<span class='npc'>[Tieve]</span>")
		NewTask = NewTask.replace(/{TRADE:npc}/gi, "<span class='npc'>[Marketplace]</span>")
		NewTask = NewTask.replace(/{TRADE_MORVAN:npc}/gi, "<span class='npc'>[Marketplace]</span>")
		NewTask = NewTask.replace(/{TRADE_ROCHEST:npc}/gi, "<span class='npc'>[Marketplace]</span>")
		NewTask = NewTask.replace(/{TRADER:npc}/gi, "<span class='npc'>[Schulivan]</span>")
		NewTask = NewTask.replace(/{TRISTAN:npc}/gi, "<span class='npc'>[Tristan]</span>")
		NewTask = NewTask.replace(/{TUREN:npc}/gi, "<span class='npc'>[Turhan]</span>")
		NewTask = NewTask.replace(/{TUREN_EP4:npc}/gi, "<span class='npc'>[Turhan]</span>")
		NewTask = NewTask.replace(/{TURKEY:npc}/gi, "<span class='npc'>[Drumstick]</span>")
		NewTask = NewTask.replace(/{UPGRADE:npc}/gi, "<span class='npc'>[Enchant]</span>")
		NewTask = NewTask.replace(/{VERAFIM:npc}/gi, "<span class='npc'>[Verafim]</span>")
		NewTask = NewTask.replace(/{WATCHTOWER:npc}/gi, "<span class='npc'>[Lookout Tower]</span>")
		NewTask = NewTask.replace(/{WEIRDCAT:npc}/gi, "<span class='npc'>[Eccentric Traveler]</span>")
		NewTask = NewTask.replace(/{YELLOW_PUMPKIN:npc}/gi, "<span class='npc'>[The Yellow Pumpkin]</span>")
		NewTask = NewTask.replace(/{YES:npc}/gi, "<span class='npc'>[YES]</span>")
		NewTask = NewTask.replace(/{YOUNGKIAHN:npc}/gi, "<span class='npc'>[Young Kean]</span>")
		NewTask = NewTask.replace(/{YOUSETY:npc}/gi, "<span class='npc'>[Yusey]</span>")
		NewTask = NewTask.replace(/{BERBE_BELL:npc}/gi, "<span class='npc'>[종탑]</span>")
		NewTask = NewTask.replace(/{BERBHE_BLACKSMITH:npc}/gi, "<span class='npc'>[대장간]</span>")
		NewTask = NewTask.replace(/{BERBHE_INN:npc}/gi, "<span class='npc'>[여관]</span>")
		NewTask = NewTask.replace(/{BERBHE_STORE:npc}/gi, "<span class='npc'>[잡화점]</span>")
		NewTask = NewTask.replace(/{BERBHE_TEMPLE:npc}/gi, "<span class='npc'>[신전]</span>")
		NewTask = NewTask.replace(/{CAITHLEANN:npc}/gi, "<span class='npc'>[카흘린]</span>")
		NewTask = NewTask.replace(/{FURYMACE:npc}/gi, "<span class='npc'>[퓨리메이스]</span>")
		NewTask = NewTask.replace(/{GERTRUD:npc}/gi, "<span class='npc'>[게르트루트]</span>")
		NewTask = NewTask.replace(/{GREMLIN_KID:npc}/gi, "<span class='npc'>[새끼 그렘린]</span>")
		NewTask = NewTask.replace(/{HARKISH:npc}/gi, "<span class='npc'>[하키쉬]</span>")
		NewTask = NewTask.replace(/{JORNIN:npc}/gi, "<span class='npc'>[요르닌]</span>")
		NewTask = NewTask.replace(/{MACHINA:npc}/gi, "<span class='npc'>[마키나]</span>")
		NewTask = NewTask.replace(/{REMU:npc}/gi, "<span class='npc'>[레무]</span>")
		NewTask = NewTask.replace(/{ROMU:npc}/gi, "<span class='npc'>[로무]</span>")
		NewTask = NewTask.replace(/{SIXEYE:npc}/gi, "<span class='npc'>[식스아이]</span>")
		NewTask = NewTask.replace(/{SPINOS:npc}/gi, "<span class='npc'>[스피노스]</span>")
		NewTask = NewTask.replace(/{TELEPORT_BERBE:npc}/gi, "<span class='npc'>[무인 상점]</span>")
		$(this).html(NewTask)
})
}